### ISSUE TITLE
PR in Spark

### ISSUE THREAD

**Issue by kpowerinfinity** [yu-iskw/hierarchical-clustering-with-spark#1]
Hello there,

I saw the comment on [SPARK-2429](https://issues.apache.org/jira/browse/SPARK-2429) but if it finally got resolved or it's still waiting on some updates (I noticed something about a bug in breeze). I am really looking forward to using this - so wanted to check the status.

Thanks!
Krishna.

**Comment by yu-iskw** [comment]
Hi Krishna, 

Thank you for commenting.
We are still tackling to merge it to Spark. And I'd like to finish this issue in a few weeks.
Please wait for a little bit time.

https://github.com/apache/spark/pull/5267

Thanks 
Yu

**Comment by kpowerinfinity** [comment]
Thank you very much!

**Comment by yu-iskw** [comment]
If you have any idea to improve my implementation, we can talk about that at Spark Summit 2015. -- Yu
